### ISSUE TITLE
Option to disable event list

### ISSUE THREAD

**Issue by ghost** [teelolws/WhereTheZaralek#5]
Hello,

Thank you for the addon!
Any chance we can get a toggle to disable this event list?
I only want the pin and taskbar flash :)
Thanks

![image](https://user-images.githubusercontent.com/122007087/237024315-c7f3dcc7-728d-4501-b13c-32f71a9c7d88.png)

**Comment by teelolws** [comment]
Yeah this is something I'm working on. The plan is to hide it during edit mode like this:

![image](https://user-images.githubusercontent.com/49792789/237056238-64c035b8-2b90-4510-b858-a58746ffac6d.png)

**Comment by ghost** [comment]
Wonderful thank you!

**Comment by ghost** [comment]
Update after some testing - the option to hide it does not persist. List shows up again.
Also, the window in edit mode feels very awkward to use tbh. Too many unnecessary clicks - why have 2 windows?
Its weird that this is even a part of edit mode tbh - all other addons do this via regular settings which makes more sense.
Just my 2 cents. Thanks.

**Comment by teelolws** [comment]
The second click is because I cannot do conditional edit mode - it would show up even if you're not in Zaralek Caverns.

Why Edit Mode? I needed to provide a way to move it, and I've previously [already written code to hook more frames into Edit Mode to do so](https://www.curseforge.com/wow/addons/edit-mode-expanded)

I'll do some testing about the hide issue.

**Comment by teelolws** [comment]
Found the problem - code to hide it was lost during a code merge with another developer yesterday: https://github.com/teelolws/WhereTheZaralek/commit/5c441cafc27b6d08fde2c89173e585b900158aea#diff-c845180126d2e68b0d6cc254312caa5a23e1ad57d7f7dcac1ae9d011eb51938b

**Comment by ghost** [comment]
Thank you :)
